[[mgr.append_keymap]]
on = ["g", "p"]
run = "cd ~/Projects"

[[mgr.append_keymap]]
on = ["g", "w"]
run = "cd ~/Documents/work"

[[mgr.append_keymap]]
on = ["g", "o"]
run = "cd ~/Documents/notes"

[[mgr.prepend_keymap]]
on = [ "g", "t" ]
run = "plugin recycle-bin"
desc = "Open Recycle Bin menu" 

[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "cd back to the root of the current Git repository"
