[[mgr.append_keymap]]
on = ["g", "p"]
run = "cd ~/Projects"

[[mgr.append_keymap]]
on = ["g", "w"]
run = "cd ~/Documents/work"

[[mgr.prepend_keymap]]
on = "!"
for = "unix"
run = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on = "f"
run = "plugin jump-to-char"
desc = "Jump to file starting with char"

[[mgr.prepend_keymap]]
on = "<C-d>"
run = "plugin diff"
desc = "Diff selected with hovered file"
