# ----------------------------------------------------
# Systems
# ----------------------------------------------------

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format", args = ["--style=LLVM"] }

[[language]]
name = "rust"
auto-format = true

# ----------------------------------------------------
# Scripting
# ----------------------------------------------------

[[language]]
name = "bash"
auto-format = true
file-types = ["sh"]
formatter = { command = "shfmt", args = ["-i", "2", "-ci"] }

[[language]]
name = "lua"
auto-format = true
formatter = { command = "stylua", args = ["-"] }

[[language]]
name = "python"
auto-format = true
language-servers = ["pyright"]
formatter = { command = "ruff", args = ["format", "-"] }

# ----------------------------------------------------
# Infrastructure
# ----------------------------------------------------

[[language]]
name = "hcl"
auto-format = true
language-servers = ["tofu-ls"]

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }

# ----------------------------------------------------
# Web
# ----------------------------------------------------

[[language]]
name = "html"
language-servers = [
  { name = "vscode-html-language-server", except-features = [
    "format",
  ] },
  "tailwindcss-ls",
  "biome",
]

[[language]]
name = "css"
language-servers = [
  { name = "vscode-css-language-server", except-features = [
    "format",
  ] },
  "tailwindcss-ls",
  "biome",
]

[[language]]
name = "javascript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "astro"
auto-format = true
language-servers = ["astro-ls", "tailwindcss-ls", "biome"]

[[language]]
name = "svelte"
auto-format = true
language-servers = ["svelteserver", "tailwindcss-ls", "biome"]

# ----------------------------------------------------
# Configs
# ----------------------------------------------------

[[language]]
name = "json"
language-servers = [
  { name = "vscode-json-language-server", except-features = [
    "format",
  ] },
  "biome",
]

[[language]]
name = "markdown"
roots = [".zk"]
language-servers = ["zk"]

# ----------------------------------------------------
# LSP
# ----------------------------------------------------

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]

[language-server.tofu-ls]
command = "tofu-ls"
args = ["serve"]

[language-server.zk]
command = "zk"
args = ["lsp"]

# [language-server.clangd]
# command = "clangd"
# args = ["--clang-tidy", "-j=5", "--malloc-trim"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
show-fixes = true
target-version = "py313"
lint = { preview = true }
format = { docstring-code-format = true, preview = true }

[language-server.rust-analyzer.config]
check.command = "clippy"
