timeout 60 'swaylock --config ~/.config/sway/swaylock.conf --ignore-empty-password --daemonize'
timeout 65 'swaymsg "output * power off"' resume 'swaymsg "output * power on"'
timeout 120 'systemctl suspend'
