timeout 150 'swaymsg "output * power off"' resume 'swaymsg "output * power on"'
timeout 160 'swaylock --config ~/.config/sway/swaylock.conf --ignore-empty-password --daemonize'
timeout 300 'systemctl suspend'
